export const Data = {
  Categories: [
    {
      id: '1',
      categoryName: 'Chocolate Cookies',
      categoryImage: require('./Assets/chocolate.png'),
    },
    {
      id: '2',
      categoryName: 'vanilla cookies',
      categoryImage: require('./Assets/vanilla.png'),
    },
    {
      id: '3',
      categoryName: 'frosted cookies',
      categoryImage: require('./Assets/frosted.png'),
    },
    {
      id: '4',
      categoryName: 'fruit and nuts cookies',
      categoryImage: require('./Assets/fruit.png'),
    },
    {
      id: '5',
      categoryName: 'ice cream cookies',
      categoryImage: require('./Assets/icecream.png'),
    },
    {
      id: '6',
      categoryName: 'cookies cake',
      categoryImage: require('./Assets/cake.png'),
    },
  ],
  Products: [
    {
      id: '2',
      CategoryId: '1',
      productName: 'Peanut Butter Chocolate Chunk',
      images: require('./Assets/chocolate2.png'),
      description:
        'Organic peanut butter weds chocolate in its ultimate union.  A salty and sweet interplay of flavors arouse your taste buds with creamy, smooth peanut butter with the perfect blend of milk and dark chocolate.  And they live happily ever after.',
      price: '5',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '3',
      CategoryId: '1',
      productName: 'Macadamia White Chocolate Chunk',
      images: require('./Assets/chocolate3.png'),
      description:
        'The irresistible duo of buttery, crunchy, dry-roasted Hawaiian macadamia nuts and silky white chocolate make these rich decadent obsessions crave-worthy.  Once you get your hands on these, you will never want to let them go.',
      price: '5',
      bgcolor: '#FEFCFC',
      added: 0,
    },

    {
      id: '5',
      CategoryId: '1',
      productName: 'Hazelnut Stuffed Cookie',
      images: require('./Assets/chocolate5.png'),
      description:
        "Big, thick, chunky cookies infused with hazelnut nuttiness. Get slapped in the face with an organic hazelnut spread filling in the middle that'll get your mouth nice and wet.",
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '6',
      CategoryId: '1',
      productName: 'M&M & Chocolate Chip Cookies',
      images: require('./Assets/chocolate6.png'),
      description:
        'This cookies come individually wrapped and boxed with care. Perfect for gifts, parties or to snack.Enjoy the chocolate chips along with pink, white and red M&Ms.',
      price: '5',
      bgcolor: '#FEFCFC',
      added: 0,
    },

    {
      id: '7',
      CategoryId: '1',
      productName: 'Chocolate Chunk Cookie',
      images: require('./Assets/chocolate7.png'),
      description:
        'The cookie that started it all for us! 3 kinds of Chocolate and pure butter in a vanilla batter. A Classic Choc Chunk Cookie.',
      price: '5',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '8',
      CategoryId: '1',
      productName: 'Oatmeal Dark Chocolate Cookie',
      images: require('./Assets/chocolate8.png'),
      description:
        'Using premium rolled oats and dark Belgian chocolate this one is a must for all you oatmeal fans!',
      price: '5',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '9',
      CategoryId: '1',
      productName: 'Fudged up',
      images: require('./Assets/chocolate9.png'),
      description:
        "What do you get when you combine crumbled fudge cookies, premium Belgian dark chocolate and a sinful injection of fudge frosting? A cookie like you've never had before, that's what.",
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '10',
      CategoryId: '1',
      productName: 'Double Chocolate Peppermint Cookie',
      images: require('./Assets/chocolate10.png'),
      description:
        'They’re fat, they’re gooey, they’re fudgy, they’re thick chocolatey cookies with Belgian milk chocolate and candy cane sand!',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '1',
      CategoryId: '1',
      productName: 'Triple Chocolate',
      images: require('./Assets/chocolate1.png'),
      description:
        'A blend of dark chocolate, milk chocolate, and dark Belgian cocoa- a chocolate lover’s dream come true!  These dangerously decadent triple threats will satisfy all of your deepest, darkest chocolate cravings and chocoholic desires.  Enjoyment triples with each bite.  You’ll keep coming back for more and more and more.',
      price: '5',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '4',
      CategoryId: '1',
      productName: 'Chocolate Dipped Chocolate Chip Cookies',
      images: require('./Assets/chocolate4.png'),
      description:
        "Taking our most popular cookie to the next level by dunking it half-way in melted chocolate.  This is our premium cookies and we promise you'll love it! ",
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '11',
      CategoryId: '2',
      productName: 'Vanilla Rich Chocolate Chip Cookies',
      images: require('./Assets/vanilla11.png'),
      description:
        'Flavors of premium vanilla and chocolate blend together to make a wonderful combination in these favorite chocolate chip cookies.',
      price: '5',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '12',
      CategoryId: '2',
      productName: 'Vanilla White Chocolate Peanut Butter Cookies',
      images: require('./Assets/vanilla12.png'),
      description:
        'These sof and Chewy peanut butter cookies are dressed up by using White Chocolate Peanut Butter, white chocolate chips extra vanilla and even a vanilla bean.  ',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '13',
      CategoryId: '2',
      productName: 'bergers style cookies',
      images: require('./Assets/vanilla13.png'),
      description:
        'Soft vanilla cookies are topped with a rich fudge-like frosting that will take your breath away.',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '14',
      CategoryId: '2',
      productName: 'Vanilla Bean Snickerdoodles',
      images: require('./Assets/vanilla14.png'),
      description:
        'Soft and chewy, these Vanilla Bean Snickerdoodles are a family favorite. Cookies packed with flavor!',
      price: '5',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '15',
      CategoryId: '2',
      productName: 'Salted Vanilla Chip Oatmeal Cookies',
      images: require('./Assets/vanilla15.png'),
      description:
        'Plenty of vanilla, white chocolate, and a pinch of salt may just make these Salted Vanilla Chip Oatmeal Cookies your new favorite!',
      price: '5',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '16',
      CategoryId: '2',
      productName: 'Cherry Vanilla Cookies',
      images: require('./Assets/vanilla16.png'),
      description:
        'Cherry Vanilla Cookies are moist, chewy, and full of creamy vanilla and tart cherry flavor. A delicious twist on the classic chocolate chip cookie!',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '17',
      CategoryId: '2',
      productName: 'Vanilla on Vanilla Sandwich Cookies',
      images: require('./Assets/vanilla17.png'),
      description:
        'Vanilla Sandwich Cookies are crunchy on the outside, chewy on the inside, and bursting with tons of real vanilla flavor.',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '18',
      CategoryId: '2',
      productName: 'Vanilla Honey Cookies',
      images: require('./Assets/vanilla18.png'),
      description:
        'Warm vanilla honey cookies stuffed with sugar and spice and everything nice.vanilla and honey play nice alongside a series of spices in these crisp and chewy cookies',
      price: '5',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '19',
      CategoryId: '2',
      productName: 'Healthy Honey Lemon Oatmeal Cookies',
      images: require('./Assets/vanilla19.png'),
      description:
        "It's cookie time! Lemon Honey Oatmeal Cookies. So delicious - I think they are perfect for Easter and well anytime! ",
      price: '5',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '20',
      CategoryId: '2',
      productName: 'Soft Vanilla Bean Sugar Cookies',
      images: require('./Assets/vanilla20.png'),
      description:
        'These vanilla bean sugar cookies are rolled in sugar for a sparkling appearance and a soft, light and chewy texture that will make these your new favorite!',
      price: '5',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '21',
      CategoryId: '3',
      productName: 'Soft Lofthouse Style Frosted Sugar Cookie',
      images: require('./Assets/frosted21.png'),
      description:
        'Perfectly Soft Lofthouse Style Frosted Sugar Cookies made from scratch with an easy frosting and full of pretty sprinkles!  Best of all, they make a delicious treat to serve with a tall glass of milk.',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '22',
      CategoryId: '3',
      productName: 'Peppermint Frosted Sugar Cookies',
      images: require('./Assets/frosted22.png'),
      description:
        'Soft Peppermint Cookies with Easy Cookie Frosting... A brilliant sugar cookie variation for the holidays',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '23',
      CategoryId: '3',
      productName: 'Frosted Sugar Cookie Bars',
      images: require('./Assets/frosted23.png'),
      description:
        'These frosted sugar cookie bars are soft, chewy, and topped with creamy vanilla buttercream. And sprinkles… of course!',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '24',
      CategoryId: '3',
      productName: 'Springtime Frosted Chocolate Cookies',
      images: require('./Assets/frosted24.png'),
      description:
        'Our Springtime Frosted Chocolate Cookies are sweet, chocolatey and covered with our deliciously creamy Best Buttercream Frosting in colorful Spring colors. ',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '25',
      CategoryId: '3',
      productName: 'Frosted Toffee Cookies',
      images: require('./Assets/frosted25.png'),
      description:
        'These delicious cookies have chocolate covered toffee in the cookie dough and sprinkled on top.Frosted Toffee cookies are a great combination of a delicious cookie bottom topped with frosting and chocolate toffee bits.',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '26',
      CategoryId: '3',
      productName: 'Red Velvet Cookies with Cream Cheese Frosting',
      images: require('./Assets/frosted26.png'),
      description:
        'If you love Lofthouse cookies – then you definitely need to try these Red Velvet Cookies with Cream Cheese Frosting. They’re pillowy soft with a delicate crumb, delicious red velvet flavor, and cream cheese frosting.',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '27',
      CategoryId: '3',
      productName: 'Glazed Almond Sugar Cookies',
      images: require('./Assets/frosted27.png'),
      description:
        'Need a new holiday cookie? Whip up this tasty sugar cookie with loads of almond flavoring.',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '28',
      CategoryId: '3',
      productName: 'Fudgy Frosted Brownie Cookies',
      images: require('./Assets/frosted28.png'),
      description:
        'Love deep, dark fudgy chocolate? Whip up a batch of cookies in no time.best for chocolate lovers.',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '29',
      CategoryId: '3',
      productName: 'Banana Nut Frosted Cookies',
      images: require('./Assets/frosted29.png'),
      description:
        'These Banana Nut Frosted Cookies are so soft and chewy, are frosted with banana cream cheese frosting and topped with chopped walnuts. ',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '30',
      CategoryId: '3',
      productName: 'Carrot Cake Cookies',
      images: require('./Assets/frosted30.png'),
      description:
        ' These Carrot Cake Cookies are perfectly portable, perfectly tender, and perfectly melt-in-your-mouth addicting. They encapsulate everything you love about Carrot Cake with its aromatic fragrant spices, carrots and pecans rolled into easy-to-make chewy cookie form. ',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '31',
      CategoryId: '4',
      productName: 'Fruit Pizza Cookies.',
      images: require('./Assets/fruit31.png'),
      description:
        'A mini version of the classic fruit pizza everyone loves! Soft sugar cookies with cream cheese frosting and colorful fruit toppings.',
      price: '7',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '32',
      CategoryId: '4',
      productName: 'Nuts and Fruits Breakfast Cookies',
      images: require('./Assets/fruit32.png'),
      description:
        'Breakfast cookies packed with fruits, nuts, oats, and everything else healthy. A delicious breakfast on-the-go!',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '33',
      CategoryId: '4',
      productName: 'Jammy Fruit Bars Recipe',
      images: require('./Assets/fruit33.png'),
      description:
        'Fruit bars that are a perfect vehicle for market-fresh blueberries, cherries, and peaches in season, or your favorite jam during those times in between.',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '34',
      CategoryId: '4',
      productName: 'Chocolate Covered Strawberry',
      images: require('./Assets/fruit34.png'),
      description:
        'Chocolate covered strawberries....meet your match. Cookie covered strawberry jam. For those that love chocolate and strawberries this would be a match made in heaven',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '35',
      CategoryId: '4',
      productName: 'Almond Chocolate Chunk Cookies',
      images: require('./Assets/fruit35.png'),
      description:
        'Thick and chewy Almond Amaretto Chocolate Chunk Cookies! These are so flavorful and one of the BEST cookie. If you love almonds and chocolate, you have to try them!',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '36',
      CategoryId: '4',
      productName: 'Cashew Nut Cookies with Dark Chocolate',
      images: require('./Assets/fruit36.png'),
      description:
        'Chunky, soft center, crispy edge cashew cookies chock full of cashews and dark chocolate chips.These cookies are chunky, chock full of cashews and dark chocolate chips and very gooey. They taste just like cashews.',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '37',
      CategoryId: '4',
      productName: 'Strawberry Shortcake Cookies',
      images: require('./Assets/fruit37.png'),
      description:
        'Strawberry shortcake cookies are a sweet way to use fresh strawberries when they are in season. The cookies are similar to scones and have a light and fluffy texture.',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '38',
      CategoryId: '4',
      productName: 'Cranberry Orange Cookies',
      images: require('./Assets/fruit38.png'),
      description:
        'These Cranberry Orange Cookies are the perfect Christmas cookie! Chewy cookies chock full of fresh cranberries and zesty orange, topped with a brightly flavored,orange glaze.',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '39',
      CategoryId: '4',
      productName: 'Healthy Raspberry Oatmeal Cookies ',
      images: require('./Assets/fruit39.png'),
      description:
        'The softest & chewiest oatmeal cookies you’ll ever eat, studded with fresh raspberries. Nobody will ever believe they’re healthy & less than 100 calories!',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '40',
      CategoryId: '4',
      productName: 'Blueberry Oat Cookies',
      images: require('./Assets/fruit40.png'),
      description:
        'These reduced sugar soft oat cookies are sweetened with Truvia and blueberries and make the ideal accompaniment to your cup of tea and coffee at elvenses.',
      price: '6',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '41',
      CategoryId: '5',
      productName: 'Mint Choc Chip Ice Cream Sandwiches',
      images: require('./Assets/icecream41.png'),
      description:
        'These vegan ice cream sandwiches are the perfect indulgent dessert that are also healthy and packed with superfoods. Raw and gluten free too.',
      price: '10',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '42',
      CategoryId: '5',
      productName: 'Vegan Chocolate ice cream Cookie',
      images: require('./Assets/icecream42.png'),
      description:
        'These Vegan Chocolate Black Bean Cookie Ice Cream Sandwiches taste super decadent but are surprisingly healthy!',
      price: '10',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '43',
      CategoryId: '5',
      productName: 'Chocolate Cookie Ice Cream Sandwiches',
      images: require('./Assets/icecream43.png'),
      description:
        'These have a big ol’ hunk of cool, creamy, refreshing ice cream sandwiched between two sink-your-teeth-into chocolate cookies',
      price: '10',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '44',
      CategoryId: '5',
      productName: 'Peanut Butter Cookie Ice Cream',
      images: require('./Assets/icecream44.png'),
      description:
        'Calling all peanut butter lovers! These easy peanut butter cookie ice cream sandwiches are made with flourless peanut butter cookies and peanut butter swirl ice cream. This is the ultimate summer dessert!',
      price: '10',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '45',
      CategoryId: '5',
      productName: 'Double Chocolate Chip Cookie Ice Cream Sandwiches',
      images: require('./Assets/icecream45.png'),
      description:
        'Creamy vanilla ice cream sandwiched between crisp and buttery sugar cookies. These sugar cookie ice cream sandwiches are the perfect summer dessert!',
      price: '10',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '46',
      CategoryId: '5',
      productName: 'chocolate chip ice cream cookies ',
      images: require('./Assets/icecream46.png'),
      description:
        'With tender chocolate chip cookies and a fluffy no-churn ice cream, these frozen treats taste just like your favorite chocolate chip cookie ice cream sandwich, only better.',
      price: '10',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '47',
      CategoryId: '5',
      productName: 'Chocolate Chip Cookie & Brownie Sandwich ',
      images: require('./Assets/icecream47.png'),
      description:
        'What happens when you marry the best chocolate chip cookie ever with the best chocolate brownie ever. Magical Crowniewich babies. (Cookies + Brownies + Sandwich = Crowniewich or Crownie for short)',
      price: '10',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '48',
      CategoryId: '5',
      productName: 'Coconut ice cream with chocolate cookies ',
      images: require('./Assets/icecream48.png'),
      description:
        'These Chocolate Cookie Ice Cream Sandwiches with No Churn Toasted Coconut Ice Cream will be perfect for all of your summer shindigs!',
      price: '10',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '49',
      CategoryId: '5',
      productName: 'Lemon ice cream Cookie Sandwiches',
      images: require('./Assets/icecream49.png'),
      description:
        'Lemon Sugar Cookie Sandwiches are sugar cookies with a splash of lemon flavoring and coloring sandwiching a creamy vanilla icecream in between. If you love sandwich cookies must try this.',
      price: '10',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '50',
      CategoryId: '5',
      productName: 'Cookie Dough Ice Cream Sandwiches',
      images: require('./Assets/icecream50.png'),
      description:
        'Cookie Dough Ice Cream Sandwiches are the perfect treat anytime, anywhere. Frozen ice cream bar with safe to eat, egg-free cookie dough.',
      price: '10',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '51',
      CategoryId: '6',
      productName: 'vanilla and chocolate chip heart strings cookie cake',
      images: require('./Assets/cake51.png'),
      description:
        'Share the love in a big way with a 12" pre-decorate chocolate chip cookie cake. A moist and chewy, colossal cookie cake. Made with real butter, whole eggs, and pure vanilla, this same irresistible cookie-dough recipe was perfected some thirty years ago and still surprises and delights thousands of loved ones each year. Our Big Cookie Cakes are still first in flavor. Cookie frosting colors are as shown.',
      price: '40',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '52',
      CategoryId: '6',
      productName: 'Chocolate Chip Cookie Cake',
      images: require('./Assets/cake52.png'),
      description:
        'A soft, chewy cookie cake filled with chocolate chips and topped with a chocolate buttercream frosting. This Chocolate Chip Cookie Cake is the perfect dessert for any occasion! Perfect for birthdays or just about any occasion and Super delicious!',
      price: '40',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '53',
      CategoryId: '6',
      productName: 'Peanut Butter Cookie Cake',
      images: require('./Assets/cake53.png'),
      description:
        "Love peanut butter?  This deep dish peanut butter cookie cake is topped with Peanut Butter , chips and chocolate drizzle.Sink your teeth into a slice of our one of a kind, deep dish cookie cake. This peanut butter creation is a combination of a giant cookie that's over an inch .",
      price: '40',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '54',
      CategoryId: '6',
      productName: 'Triple Chocolate Cookie Cake',
      images: require('./Assets/cake54.png'),
      description:
        'Dark chocolate cookie cake filled with creamy white chocolate chips and topped with a chocolate fudge frosting.',
      price: '40',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '55',
      CategoryId: '6',
      productName: 'nutella stuffed skillet cookie',
      images: require('./Assets/cake55.png'),
      description:
        'Buttery chocolate chip cookie dough, baked in a skillet, with a thick layer of Nutella hidden in the middle. Once baked, you’ll end up with a golden brown cookie with crisp edges, a slightly under cooked middle, and Nutella oozing everywhere! ',
      price: '45',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '56',
      CategoryId: '6',
      productName: 'Confetti Cookie Cake',
      images: require('./Assets/cake56.png'),
      description:
        'Large sugar cookie baked with white chocolate chips and sprinkles! perfect for birthday .',
      price: '40',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '57',
      CategoryId: '6',
      productName: 'Red Velvet Cookie Cake',
      images: require('./Assets/cake57.png'),
      description:
        'It’s time for all things Red Velvet! This Red Velvet Cookie Cake is so good, and so perfect for Valentine’s Day or anytime you need a cookie cake.',
      price: '40',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '58',
      CategoryId: '6',
      productName: 'Layered Ice Cream Cookie Cake',
      images: require('./Assets/cake58.png'),
      description:
        "A decadent layered 'cake' made with ice cream and cookies is a great way to celebrate.",
      price: '45',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '59',
      CategoryId: '6',
      productName: 'Chocolate Chip Cookie Dough Cake',
      images: require('./Assets/cake59.png'),
      description:
        "A birthday cake worthy of a party of its own! Using cookie crumbs creates cookie dough-like nuggets within the cake once it's baked. It's topped with fluffy chocolate buttercream frosting for a final flourish.",
      price: '50',
      bgcolor: '#FEFCFC',
      added: 0,
    },
    {
      id: '60',
      CategoryId: '6',
      productName: 'Chocolate Chip Cookie Ice Cream Cake',
      images: require('./Assets/cake60.png'),
      description:
        "This Chocolate Chip Cookie Ice Cream Cake is a fun cross between chocolate chip cookies and ice cream, and it's the perfect treat for summer!",
      price: '50',
      bgcolor: '#FEFCFC',
      added: 0,
    },
  ],
};
