export default {
    // USER_INFO: 'USER_INFO',
    // SET_CURRENT_PRODUCT: 'SET_CURRENT_PRODUCT',
    SET_FAVOURITE: 'SET_FAVOURITE',
    REMOVE_FAVOURITE: 'REMOVE_FAVOURITE',
    ADD_ITEM_CART: 'ADD_ITEM_CART',
    REMOVE_ITEM_CART: 'REMOVE_ITEM_CART',
    RESET_CART: 'RESET_CART',
  };
  